### PR TITLE
Adjusting some locations

### PR DESCRIPTION
**Pull request by ukilop**
In Cathedral:
- spread the locations a bit for less overlap

In Grand Library:
-  made individual locations for each chest

### CODE REVIEW

**Comment by ukilop** [comment]
im unsure why the diff on locations_pop_er is so extreme

**Review by ScipioWright — APPROVED** [review]
I think the change makes it look nicer overall

**Comment by ukilop** [comment]
Above changes:
- Re-add Fullmap
- shrink well, shop, garden knight, and guard captain location to mark as slightly less important.

**Comment by ScipioWright** [comment]
Should probably add the fullmap to the other layout variations too

**Review by patrickwhite256 — APPROVED** [review]

**Pull request merged**
